logging:
  file:
    path: logs  # ?? ?? ?? ??
  logback:
    rollingpolicy:
      file-name-pattern: logs/api-%d{yyyy-MM-dd}.log  # ??? ?? ?? ??
      max-file-size: 500MB  # ?? ?? ??? ?? ??
      max-history: 10  # ?? 10?? ?? ?? ??
  level:
    root: info  # ?? ?? ??
    org.msa.item-service: debug  # ?? ??? ?? ?? ??
