spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config # make dir config.
        encrypt:
          enabled: true

server:
  port: 8080