logging:
  file:
    name: /logs/authentication.log  # 로그 파일 경로 및 파일명 지정
    max-size: 500MB
    max-history: 10
  level:
    root: info  # 기본 로그 레벨은 info
    org.msa.autentication-server: debug  # 'org.msa.item-service' 패키지 아래는 debug 레벨

spring:
  datasource:
    uri: jdbc:mysql://localhost:3306/msa
    username: root
    password: '{cipher}20236f835eafe8560e3a8a6e7262e5b85baebd9b2e60aa98d5958c2f877cc9a2'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  # 개발 환경에서는 'update', 운영에서는 'none' 권장
    properties:
      hibernate:
        format_sql: true
        show_sql: true  # 콘솔에 SQL 로그 출력


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
