spring:
  datasource:
    uri: jdbc:mysql://localhost:3306/msa
    username: root
    password: '{cipher}20236f835eafe8560e3a8a6e7262e5b85baebd9b2e60aa98d5958c2f877cc9a2'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  # 개발 환경에서는 'update', 운영에서는 'none' 권장
    properties:
      hibernate:
        format_sql: true
        show_sql: true  # 콘솔에 SQL 로그 출력
logging:
  file:
    name: /logs/api.log  # 로그 파일 경로 및 파일명 지정
  logback:
    rolling-policy:
      file-name-pattern: logs/api-local-%d{yyyy-MM-dd}.log  # 롤링 파일 패턴 지정
      max-file-size: 500MB  # 파일 최대 크기 설정
      max-history: 10  # 최대 10일치 로그 파일 보관
  level:
    root: info  # 기본 로그 레벨은 info
    org.msa.item-service: debug  # 'org.msa.item-service' 패키지 아래는 debug 레벨

token:
  expiration_time: 8600000
  secret: SECU100